import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { openStorage } from './storage.mjs';
import { createApp } from './app.mjs';
const dir=resolve(process.env.MAGAZOO_DATA_DIR??'.magazoo-data');
await mkdir(dir,{recursive:true,mode:0o700});
const storage=openStorage(resolve(dir,'projects.sqlite'));
const origin=process.env.MAGAZOO_ORIGIN??'http://127.0.0.1:8787';
const server=createApp({storage,origin,publicKeyFile:process.env.MAGAZOO_ADMIN_PUBLIC_KEY,staticDir:resolve('dist')});
server.listen(Number(process.env.PORT??8787),process.env.HOST??'127.0.0.1',()=>console.log(`Magazoo server ready at ${origin}. Admin: ${origin}/#admin`));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(()=>{storage.close();process.exit(0);}));
